apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app.kubernetes.io/name: fastticket-frontend
    app.kubernetes.io/part-of: fastticket
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: fastticket-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fastticket-frontend
        app.kubernetes.io/part-of: fastticket
    spec:
      containers:
        - name: frontend
          image: fastticket-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          env:
            - name: BACKEND_URL
              value: http://backend:8080
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
