apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  labels:
    app.kubernetes.io/name: fastticket-postgres
    app.kubernetes.io/part-of: fastticket
  annotations:
    description: Configuration for FastTicket PostgreSQL
data:
  POSTGRES_DB: fastticket
  POSTGRES_USER: fastticket
  POSTGRES_HOST: postgres
  POSTGRES_PORT: "5432"
