#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

PASS=true
NS="staging"
CLUSTER="fastticket-eks"
REGION="us-east-1"

check_cmd(){ command -v "$1" >/dev/null 2>&1 && echo "[OK] $1" || { echo "[MISSING] $1"; PASS=false; }; }

mkdir -p logs reports

echo "== Tools =="
check_cmd kubectl
check_cmd gh || true
check_cmd aws
check_cmd jq || true

echo "\n== Validation scripts present =="
req_scripts=(
  "infra/validate_eks_stage1.sh"
  "scripts/validate_stage2_prereqs.sh"
  "scripts/validate_stage2_deployment.sh"
  "scripts/validate_stage3_prereqs.sh"
  "scripts/validate_stage3_pipeline.sh"
  "scripts/validate_stage4_prereqs.sh"
  "scripts/validate_stage4_results.sh"
)
for f in "${req_scripts[@]}"; do
  if [ -f "$f" ]; then echo "[OK] $f"; else echo "[MISSING] $f"; PASS=false; fi
done

echo "\n== EKS access =="
set +e
aws eks update-kubeconfig --name "$CLUSTER" --region "$REGION" >/dev/null 2>&1 && echo "[OK] kubeconfig set for $CLUSTER" || echo "[WARN] Could not set kubeconfig"
kubectl get ns "$NS" >/dev/null 2>&1 && echo "[OK] namespace $NS" || echo "[WARN] namespace $NS not reachable"
set -e

echo "\n== Reports dir and prior artifacts =="
[ -d reports ] && echo "[OK] reports/ exists" || { echo "[MISSING] reports/"; PASS=false; }
ls -1 reports 2>/dev/null | grep -E 'npm-audit|pip-audit|tfsec|checkov|trivy' >/dev/null 2>&1 && echo "[OK] prior security reports present" || echo "[INFO] prior security reports not found (will be generated by workflows)"

echo "\n== AWS Cost Explorer (optional) =="
START_DATE=$(date -v-7d +%Y-%m-%d 2>/dev/null || date -d "7 days ago" +%Y-%m-%d)
END_DATE=$(date +%Y-%m-%d)
set +e
aws ce get-cost-and-usage --time-period Start=$START_DATE,End=$END_DATE --granularity DAILY --metrics UnblendedCost >/dev/null 2>&1 && echo "[OK] AWS Cost Explorer accessible" || echo "[INFO] Cost Explorer not accessible with current creds (optional)"
set -e

if [ "$PASS" = true ]; then
  echo "\nRESULT: PASS - Stage 5 prerequisites look good."
else
  echo "\nRESULT: FAIL - Please address the missing items above."
fi
