apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - storageclass-gp3.yaml
  - postgres/secret.yaml
  - postgres/configmap.yaml
  - postgres/service.yaml
  - postgres/statefulset.yaml
  - backend/deployment.yaml
  - backend/service.yaml
  - frontend/deployment.yaml
  - frontend/service.yaml
labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: true
    includeTemplates: true
