name: CI

on:
  push:
    branches-ignore: ["main"]
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  backend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps (backend)
        working-directory: api
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unit tests (backend)
        working-directory: api
        run: |
          pytest -q --maxfail=1 --disable-warnings

  frontend-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install deps (frontend)
        working-directory: frontend
        run: |
          npm ci

      - name: Build (frontend)
        working-directory: frontend
        run: |
          npm run build --if-present

      - name: Run unit tests (frontend)
        working-directory: frontend
        run: |
          npm test --silent --ignore-scripts --if-present || npm run test --silent || true
        env:
          CI: 'true'

  sca-security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Python SCA (pip-audit)
        working-directory: api
        run: |
          pip install pip-audit
          pip-audit -r requirements.txt -f json -o ../reports/pip-audit.json || true

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Node SCA (npm audit)
        working-directory: frontend
        run: |
          npm ci
          npm audit --audit-level=high --json > ../reports/npm-audit.json || true

      - name: Upload SCA reports
        uses: actions/upload-artifact@v4
        with:
          name: sca-reports
          path: |
            reports/pip-audit.json
            reports/npm-audit.json
          retention-days: 7

  docker-build-and-scan:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build backend image (no push)
        uses: docker/build-push-action@v6
        with:
          context: ./api
          file: ./api/Dockerfile
          push: false
          load: true
          tags: |
            fastticket-backend:ci-${{ github.sha }}
          platforms: linux/amd64

      - name: Build frontend image (no push)
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: false
          load: true
          tags: |
            fastticket-frontend:ci-${{ github.sha }}
          platforms: linux/amd64

      - name: Trivy scan backend image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: fastticket-backend:ci-${{ github.sha }}
          format: 'sarif'
          output: 'reports/trivy-backend.sarif'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true

      - name: Trivy scan frontend image
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: fastticket-frontend:ci-${{ github.sha }}
          format: 'sarif'
          output: 'reports/trivy-frontend.sarif'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: true

      - name: Upload Trivy reports
        uses: actions/upload-artifact@v4
        with:
          name: trivy-reports
          path: |
            reports/trivy-backend.sarif
            reports/trivy-frontend.sarif
          retention-days: 7
