name: React CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop ]

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  backend-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api  # path to your Python API
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q


      # Bandit scan of the code
      - name: Install Bandit
        run: pip install bandit

      - name: Run Bandit security scan
        run: bandit -r ./api -f json -o bandit-report.json



      - name: Build Docker image
        run: docker build -t emoralesc/api:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: docker push  emoralesc/api:latest


  frontend-react:    
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run tests
        working-directory: ./frontend
        run: npm test -- --coverage --watchAll=false

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info
          flags: frontend
          name: frontend-coverage
        continue-on-error: true

      - name: Build Docker image
        run: docker build -t emoralesc/api:latest -f frontend/Dockerfile frontend/

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: docker push  emoralesc/api:latest

      - name: Image digest
        run: echo ${{ steps.meta.outputs.digest }}




  codeql:
    runs-on: ubuntu-latest
    needs:
      - backend-api
      - frontend-react
    steps:
      - uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript, python
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2