name: React CI/CD Pipeline

on:
  push:
    branches: [ main, master, develop ]

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  
  codeql:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api  # path to your Python API
    steps:
      - uses: actions/checkout@v3
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: javascript, python
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          # Fail the job if vulnerabilities of severity medium or higher are detected
          fail-on: medium



  backend-api:
    runs-on: ubuntu-latest
    needs:
      - sca
    defaults:
      run:
        working-directory: ./api  # path to your Python API
    steps:
      #checkou code
      - name: Checkout code
        uses: actions/checkout@v4

      #prepare python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q --coverage




      #create docker image

      - name: Build Docker image
        run: docker build -t emoralesc/api:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: docker push  emoralesc/api:latest


  frontend-react:    
    runs-on: ubuntu-latest
    needs:
      - sca
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Run tests
        working-directory: ./frontend
        run: npm test -- --coverage --watchAll=false

      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage/lcov.info
          flags: frontend
          name: frontend-coverage
        continue-on-error: true

      - name: Build Docker image
        run: docker build -t emoralesc/api:latest -f frontend/Dockerfile frontend/

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to Docker Hub
        if: github.ref == 'refs/heads/main'
        run: docker push  emoralesc/api:latest

      - name: Image digest
        run: echo ${{ steps.meta.outputs.digest }}


  sca:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install Snyk CLI
      - name: Install Snyk CLI
        run: npm install -g snyk

      # SCA scan for Python API
      - name: Snyk Python scan
        run: snyk test --all-projects --severity-threshold=medium --sarif > snyk-python.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        working-directory: ./api

      # SCA scan for React frontend (Node.js)
      - name: Snyk Node.js scan
        run: snyk test --all-projects --severity-threshold=medium --sarif > snyk-node.sarif
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        working-directory: ./frontend

      # Optionally upload scan results to GitHub Security tab (Python)
      - name: Upload Snyk Python SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./api/snyk-python.sarif

      # Optionally upload scan results to GitHub Security tab (Node.js)
      - name: Upload Snyk Node SARIF
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: ./frontend/snyk-node.sarif
