apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
# Staging namespace isolates workloads and helps enforce resource quotas
namespace: staging
resources:
  - namespace.yaml
  - ../../base
patches:
  - path: patches.yaml
images:
  - name: fastticket-backend
    newName: docker.io/fercanap/fastticket-backend
    newTag: staging # Pin to staging tag to avoid pulling latest by accident
  - name: fastticket-frontend
    newName: docker.io/fercanap/fastticket-frontend
    newTag: staging # Use a deterministic tag for reproducible deploys
